---
apiVersion: v1
kind: Secret
metadata:
  name: my-springboot-4-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/ghrhdh1/my-springboot-4-gitops